# Generated by Django 5.2.7 on 2025-10-26 08:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Название фильма"
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=1000, verbose_name="Описание фильма"),
                ),
                (
                    "duration",
                    models.IntegerField(verbose_name="Продолжительность в минутах"),
                ),
                ("poster_url", models.URLField(verbose_name="ссылка на постер")),
            ],
            options={
                "verbose_name": "Фильм",
                "verbose_name_plural": "Фильмы",
            },
        ),
    ]
