# Generated by Django 5.2 on 2025-10-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Название фильма"
            ),
        ),
    ]
