# Generated by Django 5.2 on 2025-10-10 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movies", "0003_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hall",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название зала"
                    ),
                ),
                ("rows", models.PositiveIntegerField(verbose_name="Количество рядов")),
                (
                    "seats_per_row",
                    models.PositiveIntegerField(verbose_name="Количество мест в ряду"),
                ),
            ],
            options={
                "verbose_name": "Зал",
                "verbose_name_plural": "Залы",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(verbose_name="Время начала сеанса"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Стоимость билета"
                    ),
                ),
                (
                    "hall_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="schedule.hall",
                        verbose_name="Зал",
                    ),
                ),
                (
                    "movie_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="movies.movie",
                        verbose_name="Фильм",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сеанс",
                "verbose_name_plural": "Сеансы",
                "ordering": ["start_time"],
            },
        ),
    ]
