# Generated by Django 5.2 on 2025-10-18 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField(verbose_name="номер ряда")),
                (
                    "seat_number",
                    models.PositiveIntegerField(verbose_name="Номер места"),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schedule.hall"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hall", "row_number", "seat_number"),
                        name="unique_hall_row_number",
                    )
                ],
            },
        ),
    ]
