# Generated by Django 5.2.7 on 2025-10-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="is_free",
            field=models.BooleanField(default=True),
        ),
    ]
