# Generated by Django 5.2.7 on 2025-10-26 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0002_seat_is_free"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seat",
            name="is_free",
        ),
    ]
