# Generated by Django 5.2 on 2025-10-18 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_seat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hall",
            name="rows",
        ),
        migrations.RemoveField(
            model_name="hall",
            name="seats_per_row",
        ),
        migrations.AlterField(
            model_name="seat",
            name="hall",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="schedule.hall",
            ),
        ),
    ]
