# Generated by Django 5.2 on 2025-10-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0003_remove_hall_rows_remove_hall_seats_per_row_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seat",
            options={
                "ordering": ["hall", "row_number", "seat_number"],
                "verbose_name": "Место",
                "verbose_name_plural": "Места",
            },
        ),
        migrations.RemoveConstraint(
            model_name="seat",
            name="unique_hall_row_number",
        ),
        migrations.AddConstraint(
            model_name="seat",
            constraint=models.UniqueConstraint(
                fields=("hall", "row_number", "seat_number"),
                name="unique_hall_row_seat",
            ),
        ),
    ]
