# Generated by Django 5.2.7 on 2025-11-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0003_remove_seat_is_free"),
    ]

    operations = [
        migrations.RenameField(
            model_name="session",
            old_name="hall_id",
            new_name="hall",
        ),
        migrations.RenameField(
            model_name="session",
            old_name="movie_id",
            new_name="movie",
        ),
        migrations.AlterField(
            model_name="hall",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
