# Generated by Django 5.2.7 on 2025-10-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_booking_seats_alter_booking_session_and_more"),
        ("schedule", "0003_remove_seat_is_free"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "verbose_name": "Бронированное место",
                "verbose_name_plural": "Бронированные места",
            },
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="booking",
            name="seats",
        ),
        migrations.AddField(
            model_name="booking",
            name="seats",
            field=models.ManyToManyField(
                related_name="booked_seats", to="schedule.seat"
            ),
        ),
    ]
