# Generated by Django 5.2.7 on 2025-11-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_alter_booking_options_booking_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="task_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID задачи Celery"
            ),
        ),
    ]
