# Generated by Django 5.2 on 2025-10-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_alter_user_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
